import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js';

const canvas=document.getElementById('game');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.15;
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x08110d); scene.fog=new THREE.Fog(0x08110d,55,150);
const camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,.1,300);
const hemi=new THREE.HemisphereLight(0xbfdcff,0x162018,1.25); scene.add(hemi);
const sun=new THREE.DirectionalLight(0xffffff,3.1); sun.position.set(-35,55,20); sun.castShadow=true; sun.shadow.mapSize.set(2048,2048); sun.shadow.camera.left=-70;sun.shadow.camera.right=70;sun.shadow.camera.top=50;sun.shadow.camera.bottom=-50;scene.add(sun);

const FIELD={w:68,l:105};
const mat=(c,rough=.8)=>new THREE.MeshStandardMaterial({color:c,roughness:rough});
const pitch=new THREE.Mesh(new THREE.PlaneGeometry(FIELD.l,FIELD.w),mat(0x286b32)); pitch.rotation.x=-Math.PI/2; pitch.receiveShadow=true; scene.add(pitch);
const stripeMat=mat(0x327b3c); for(let i=0;i<13;i++){const s=new THREE.Mesh(new THREE.PlaneGeometry(FIELD.l/13,FIELD.w),stripeMat);s.rotation.x=-Math.PI/2;s.position.set(-FIELD.l/2+FIELD.l/26+i*FIELD.l/13,.006,0);scene.add(s)}
const lineMat=new THREE.MeshBasicMaterial({color:0xffffff,side:THREE.DoubleSide});
function line(x1,z1,x2,z2){const g=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(x1,.025,z1),new THREE.Vector3(x2,.025,z2)]);scene.add(new THREE.Line(g,lineMat))}
line(-FIELD.l/2,-FIELD.w/2,FIELD.l/2,-FIELD.w/2);line(-FIELD.l/2,FIELD.w/2,FIELD.l/2,FIELD.w/2);line(-FIELD.l/2,-FIELD.w/2,-FIELD.l/2,FIELD.w/2);line(FIELD.l/2,-FIELD.w/2,FIELD.l/2,FIELD.w/2);line(0,-FIELD.w/2,0,FIELD.w/2);
const circle=new THREE.Line(new THREE.BufferGeometry().setFromPoints(Array.from({length:65},(_,i)=>new THREE.Vector3(Math.cos(i*Math.PI*2/64)*9.15,.026,Math.sin(i*Math.PI*2/64)*9.15))),lineMat);scene.add(circle);
for(const sx of [-1,1]){const x=sx*(FIELD.l/2-16.5); line(x,-20.16,x,20.16); line(sx*FIELD.l/2,-20.16,x,-20.16);line(sx*FIELD.l/2,20.16,x,20.16)}

function stadium(){
 const standMat=mat(0x30363b); for(let z=-1;z<=1;z+=2){const s=new THREE.Mesh(new THREE.BoxGeometry(130,8,15),standMat);s.position.set(0,4,z*45);s.castShadow=true;scene.add(s)}
 for(let x=-1;x<=1;x+=2){const s=new THREE.Mesh(new THREE.BoxGeometry(15,8,90),standMat);s.position.set(x*61,4,0);scene.add(s)}
 for(let x=-52;x<=52;x+=13)for(const z of [-45,45]){const pole=new THREE.Mesh(new THREE.CylinderGeometry(.25,.25,18,8),mat(0x555555));pole.position.set(x,9,z);scene.add(pole);const lamp=new THREE.Mesh(new THREE.BoxGeometry(5,1,1),mat(0xffffff));lamp.position.set(x,17,z);scene.add(lamp)}
}
stadium();

const players=[]; let controlled;
function makePlayer(team,x,z,num){const group=new THREE.Group();group.position.set(x,.9,z);const body=new THREE.Mesh(new THREE.CapsuleGeometry(.42,.75,4,10),mat(team===0?0xffffff:0x17233c));body.castShadow=true;group.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.22,12,8),mat(0xc88963));head.position.y=.7;head.castShadow=true;group.add(head);const marker=new THREE.Mesh(new THREE.RingGeometry(.48,.56,20),new THREE.MeshBasicMaterial({color:0xffff00,side:THREE.DoubleSide}));marker.rotation.x=-Math.PI/2;marker.position.y=-.86;marker.visible=false;group.add(marker);group.userData={team,num,vel:new THREE.Vector3(),control:team===0?75:68,stamina:100,marker,base:new THREE.Vector3(x,.9,z),role:num===1?'GK':'OUT'};scene.add(group);players.push(group);return group}
const homePos=[[-48,0],[-30,-22],[-30,0],[-30,22],[-10,-28],[-10,-10],[-10,10],[-10,28],[15,-20],[15,0],[15,20]]; const awayPos=[[48,0],[30,-22],[30,0],[30,22],[10,-28],[10,-10],[10,10],[10,28],[-15,-20],[-15,0],[-15,20]];
homePos.forEach((p,i)=>makePlayer(0,p[0],p[1],i+1));awayPos.forEach((p,i)=>makePlayer(1,p[0],p[1],i+1)); controlled=players[9];controlled.userData.marker.visible=true;

const ball=new THREE.Mesh(new THREE.SphereGeometry(.11,24,16),new THREE.MeshStandardMaterial({color:0xffffff,roughness:.35}));ball.castShadow=true;ball.position.set(0,.11,0);scene.add(ball);
const ballState={v:new THREE.Vector3(),w:new THREE.Vector3(),mass:.43,Cd:.25,angularDrag:.05,restitution:.78,magnus:.00035,wear:0};
const keys={};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key===' ')e.preventDefault();if(e.key.toLowerCase()==='q')switchPlayer();if(e.key.toLowerCase()==='r')resetBall();if(e.key.toLowerCase()==='c')cameraMode=(cameraMode+1)%2});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
let cameraMode=0,score=[0,0],matchTime=0,shootCharge=0,shooting=false,last=performance.now(),touchTimer=0;
function resetBall(){ball.position.set(0,.11,0);ballState.v.set(0,0,0);ballState.w.set(0,0,0)}
function switchPlayer(){const team=players.filter(p=>p.userData.team===0);controlled.userData.marker.visible=false;let best=team[0],d=Infinity;for(const p of team){const q=p.position.distanceTo(ball.position);if(q<d){d=q;best=p}}controlled=best;controlled.userData.marker.visible=true}
function inputDir(){let x=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),z=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);const v=new THREE.Vector3(x,0,z);return v.lengthSq()?v.normalize():v}
function closestPlayer(){let best=null,d=999;for(const p of players){const q=p.position.distanceTo(ball.position);if(q<d){d=q;best=p}}return [best,d]}
function kick(power,curve=0,loft=.12){const dir=new THREE.Vector3();controlled.getWorldDirection(dir);dir.y=0;if(dir.lengthSq()<.1)dir.set(1,0,0);dir.normalize();const target=new THREE.Vector3().subVectors(ball.position,controlled.position);target.y=0;if(target.length()>1)dir.lerp(target.normalize(),.35).normalize();ballState.v.copy(dir).multiplyScalar(power);ballState.v.y=power*loft;ballState.w.set(0,curve*power,0);ball.position.y=Math.max(.13,ball.position.y);}
function pass(){if(controlled.position.distanceTo(ball.position)<2){kick(23,0,.025);document.getElementById('status').textContent='DRIVEN PASS';touchTimer=.35}}
function shoot(){if(controlled.position.distanceTo(ball.position)<2){const t=shootCharge;const timing=Math.abs(t-.72);let quality=timing<.09?'GREEN':timing<.22?'YELLOW':'RED';const power=16+24*Math.min(1,t);kick(power,quality==='GREEN'?1.8:quality==='YELLOW'?1.2:.7,.18);document.getElementById('timed').textContent=quality+' FINISH';document.getElementById('timed').classList.add('show');setTimeout(()=>document.getElementById('timed').classList.remove('show'),500);document.getElementById('status').textContent=quality+' FINISH';shootCharge=0;shooting=false}}
function updateControlled(dt){const d=inputDir();const sprint=keys.shift&&d.lengthSq();const max= sprint?10:6.2;const target=d.clone().multiplyScalar(max);const accel=1-Math.pow(.001,dt*(sprint?5:3));controlled.userData.vel.lerp(target,accel*.85);if(!d.lengthSq())controlled.userData.vel.multiplyScalar(Math.pow(.85,dt*60));controlled.position.addScaledVector(controlled.userData.vel,dt);controlled.position.x=THREE.MathUtils.clamp(controlled.position.x,-52,52);controlled.position.z=THREE.MathUtils.clamp(controlled.position.z,-32,32);if(d.lengthSq()){const a=Math.atan2(d.x,d.z);controlled.rotation.y=THREE.MathUtils.lerp(controlled.rotation.y,a,.18)}
 const dist=controlled.position.distanceTo(ball.position);if(dist<1.35&&!shooting&&keys.e){pass();keys.e=false}if(keys[' ']){shooting=true;shootCharge=Math.min(1,shootCharge+dt*1.25)}else if(shooting)shoot();document.querySelector('#power i').style.width=(shootCharge*100)+'%';
 if(dist<1.3&&ballState.v.length()<9&&!keys[' ']){const to=ball.position.clone().sub(controlled.position);to.y=0;if(to.length()>1.05)ball.position.addScaledVector(to.normalize(),(1.05-to.length())*.2);ballState.v.multiplyScalar(Math.pow(.25,dt))}
}
function updateAI(dt){for(const p of players){if(p===controlled)continue;const team=p.userData.team;let desired=new THREE.Vector3();const [near,nd]=closestPlayer();const threat=team===1?controlled.position:ball.position; if(team===0){desired.copy(p.userData.base);desired.x+=THREE.MathUtils.clamp(ball.position.x*.12,-8,8);desired.z+=THREE.MathUtils.clamp(ball.position.z*.18,-7,7);if(nd<10&&near.userData.team!==team)desired.lerp(ball.position,.28)}else{desired.copy(p.userData.base);desired.x+=ball.position.x*.16;desired.z+=ball.position.z*.2;if(nd<14)desired.lerp(ball.position,.22)}if(p.userData.role==='GK'){desired.x=team===0?-50:50;desired.z=THREE.MathUtils.clamp(ball.position.z*.35,-12,12)}const delta=desired.sub(p.position);delta.y=0;const max=p.userData.role==='GK'?5.5:6.3;if(delta.length()>1){delta.normalize().multiplyScalar(max);p.userData.vel.lerp(delta,1-Math.pow(.01,dt*2));p.position.addScaledVector(p.userData.vel,dt);p.rotation.y=Math.atan2(p.userData.vel.x,p.userData.vel.z)}if(p.position.distanceTo(ball.position)<1.25&&ballState.v.length()<4){const to=team===1?new THREE.Vector3(-1,0,0):new THREE.Vector3(1,0,0);ballState.v.copy(to).multiplyScalar(8);ballState.w.set(0,team===1?-1:1,0)}}}
function ballPhysics(dt){const v=ballState.v;const speed=v.length();const rho=.9,A=Math.PI*.11*.11;const drag=.5*rho*ballState.Cd*A*speed; if(speed>0)v.addScaledVector(v.clone().normalize(),-drag/ballState.mass*dt);const magnus=new THREE.Vector3().crossVectors(ballState.w,v).multiplyScalar(ballState.magnus);v.addScaledVector(magnus,dt);v.y-=9.81*dt;ball.position.addScaledVector(v,dt);ballState.w.multiplyScalar(Math.exp(-ballState.angularDrag*dt));if(ball.position.y<=.11){ball.position.y=.11;if(v.y<0)v.y=-v.y*ballState.restitution;const friction=.52;v.x*=Math.max(0,1-friction*dt);v.z*=Math.max(0,1-friction*dt);ballState.w.multiplyScalar(.985)}if(Math.abs(ball.position.x)>52.3){ball.position.x=Math.sign(ball.position.x)*52.3;v.x*=-.65}if(Math.abs(ball.position.z)>34){ball.position.z=Math.sign(ball.position.z)*34;v.z*=-.65}ball.rotation.x+=ballState.w.x*dt;ball.rotation.y+=ballState.w.y*dt;ball.rotation.z+=ballState.w.z*dt}
function goalCheck(){if(Math.abs(ball.position.x)>52&&Math.abs(ball.position.z)<3.7&&ball.position.y<2.5){score[ball.position.x>0?0:1]++;document.getElementById('score').textContent=score[0]+' — '+score[1];resetBall()}}
function pitchWear(){ballState.wear=Math.min(1,ballState.wear+.00002);pitch.material.roughness=.8+.15*ballState.wear}
function updateCamera(dt){const look=ball.position.clone();if(cameraMode===0){const desired=new THREE.Vector3(ball.position.x-30,24,ball.position.z+38);camera.position.lerp(desired,1-Math.pow(.002,dt));camera.lookAt(look.x,0,look.z)}else{const desired=controlled.position.clone().add(new THREE.Vector3(0,5.5,8));camera.position.lerp(desired,1-Math.pow(.001,dt));camera.lookAt(controlled.position.x,1,controlled.position.z)}}
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);
function animate(now){const dt=Math.min(.033,(now-last)/1000);last=now;matchTime+=dt;updateControlled(dt);updateAI(dt);ballPhysics(dt);goalCheck();pitchWear();updateCamera(dt);document.getElementById('clock').textContent=String(Math.floor(matchTime/60)).padStart(2,'0')+':'+String(Math.floor(matchTime%60)).padStart(2,'0');renderer.render(scene,camera);requestAnimationFrame(animate)}
setTimeout(()=>document.getElementById('loading').remove(),600);requestAnimationFrame(animate);
