import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js';

const canvas=document.getElementById('game');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.setSize(innerWidth,innerHeight,false);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x07110c);scene.fog=new THREE.Fog(0x07110c,70,180);
const camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.1,300);
scene.add(new THREE.HemisphereLight(0xddeaff,0x142018,1.25));
const sun=new THREE.DirectionalLight(0xffffff,3.2);sun.position.set(-35,55,25);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-75;sun.shadow.camera.right=75;sun.shadow.camera.top=65;sun.shadow.camera.bottom=-65;scene.add(sun);
const FIELD={L:105,W:68,HL:52.5,HW:34};const BALL_R=.11,PLAYER_R=.42;
const players=[];let active,score=[0,0],matchTime=0,cameraMode=0,last=performance.now(),goalLock=0;
const keys=Object.create(null),pressed=Object.create(null);
const key=e=>e.code==='Space'?'space':e.key==='Shift'?'shift':e.key.length===1?e.key.toLowerCase():e.key;
const blocked=new Set(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Space','Spacebar','Shift','w','a','s','d','e','q','r','c','W','A','S','D','E','Q','R','C']);
addEventListener('keydown',e=>{if(blocked.has(e.key)||blocked.has(e.code))e.preventDefault();const k=key(e);if(!keys[k])pressed[k]=true;keys[k]=true},{capture:true,passive:false});
addEventListener('keyup',e=>{if(blocked.has(e.key)||blocked.has(e.code))e.preventDefault();keys[key(e)]=false},{capture:true,passive:false});
addEventListener('blur',()=>{for(const k in keys)keys[k]=false});
const consume=k=>{const v=!!pressed[k];delete pressed[k];return v};
const scoreEl=document.getElementById('score'),clockEl=document.getElementById('clock'),statusEl=document.getElementById('status');
const mat=(c,r=.8)=>new THREE.MeshStandardMaterial({color:c,roughness:r});

// Pitch
const pitch=new THREE.Mesh(new THREE.PlaneGeometry(FIELD.L,FIELD.W),mat(0x2d7438,.9));pitch.rotation.x=-Math.PI/2;pitch.receiveShadow=true;scene.add(pitch);
for(let i=0;i<14;i++){const s=new THREE.Mesh(new THREE.PlaneGeometry(FIELD.L/14+.03,FIELD.W),mat(i%2?0x337d3f:0x286f35,.95));s.rotation.x=-Math.PI/2;s.position.set(-FIELD.HL+FIELD.L/28+i*FIELD.L/14,.006,0);s.receiveShadow=true;scene.add(s)}
const lm=new THREE.LineBasicMaterial({color:0xffffff});
function line(x1,z1,x2,z2){scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(x1,.028,z1),new THREE.Vector3(x2,.028,z2)]),lm))}
line(-FIELD.HL,-FIELD.HW,FIELD.HL,-FIELD.HW);line(-FIELD.HL,FIELD.HW,FIELD.HL,FIELD.HW);line(-FIELD.HL,-FIELD.HW,-FIELD.HL,FIELD.HW);line(FIELD.HL,-FIELD.HW,FIELD.HL,FIELD.HW);line(0,-FIELD.HW,0,FIELD.HW);
const circle=[];for(let i=0;i<=96;i++){const a=i*Math.PI*2/96;circle.push(new THREE.Vector3(Math.cos(a)*9.15,.03,Math.sin(a)*9.15))}scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(circle),lm));
for(const s of [-1,1]){const gx=s*FIELD.HL,bx=s*(FIELD.HL-16.5),sx=s*(FIELD.HL-5.5);line(gx,-20.16,bx,-20.16);line(bx,-20.16,bx,20.16);line(bx,20.16,gx,20.16);line(gx,-9.16,sx,-9.16);line(sx,-9.16,sx,9.16);line(sx,9.16,gx,9.16)}
function goal(side){const g=new THREE.Group(),m=mat(0xffffff,.3);for(const z of [-3.66,3.66]){const p=new THREE.Mesh(new THREE.CylinderGeometry(.06,.06,2.44,12),m);p.position.set(side*FIELD.HL,1.22,z);p.castShadow=true;g.add(p)}const b=new THREE.Mesh(new THREE.CylinderGeometry(.06,.06,7.32,12),m);b.rotation.x=Math.PI/2;b.position.set(side*FIELD.HL,2.44,0);b.castShadow=true;g.add(b);scene.add(g)}goal(-1);goal(1);

// Players
const homeFormation=[[-47,0],[-30,-22],[-30,0],[-30,22],[-10,-27],[-10,-9],[-10,9],[-10,27],[14,-18],[14,0],[14,18]];
const awayFormation=[[47,0],[30,-22],[30,0],[30,22],[10,-27],[10,-9],[10,9],[10,27],[-14,-18],[-14,0],[-14,18]];
function player(team,x,z,num){const g=new THREE.Group();g.position.set(x,.9,z);g.userData={team,num,base:new THREE.Vector3(x,.9,z),v:new THREE.Vector3(),stun:0,tackle:0,role:num===1?'GK':'OUT'};const kit=team===0?0xc51f32:0xe8edf3,shorts=team===0?0x17191d:0x25334d;const body=new THREE.Mesh(new THREE.CapsuleGeometry(.42,.76,5,12),mat(kit,.6));body.castShadow=true;g.add(body);const sh=new THREE.Mesh(new THREE.CylinderGeometry(.34,.39,.28,12),mat(shorts,.7));sh.position.y=-.55;sh.castShadow=true;g.add(sh);const head=new THREE.Mesh(new THREE.SphereGeometry(.22,16,12),mat(0xc47b5d,.7));head.position.y=.7;head.castShadow=true;g.add(head);const ring=new THREE.Mesh(new THREE.RingGeometry(.5,.61,28),new THREE.MeshBasicMaterial({color:team===0?0xff3344:0x44a4ff,side:THREE.DoubleSide,transparent:true,opacity:.8}));ring.rotation.x=-Math.PI/2;ring.position.y=-.88;g.add(ring);const marker=new THREE.Mesh(new THREE.ConeGeometry(.14,.28,4),new THREE.MeshBasicMaterial({color:0xffff00}));marker.position.y=2.1;marker.rotation.x=Math.PI;marker.visible=false;g.add(marker);g.userData.marker=marker;scene.add(g);players.push(g);return g}
homeFormation.forEach((p,i)=>player(0,p[0],p[1],i+1));awayFormation.forEach((p,i)=>player(1,p[0],p[1],i+1));active=players[9];active.userData.marker.visible=true;

// Ball
function ballTexture(){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d');x.fillStyle='#eeeeea';x.fillRect(0,0,512,512);for(let i=0;i<9000;i++){const p=190+Math.random()*55;x.fillStyle=`rgba(${p},${p},${p},${.08})`;x.fillRect(Math.random()*512,Math.random()*512,1,1)}for(let j=0;j<18;j++){const px=(j*137)%512,py=(j*83)%512;x.beginPath();for(let i=0;i<5;i++){const a=-Math.PI/2+i*Math.PI*2/5,r=31;x.lineTo(px+Math.cos(a)*r,py+Math.sin(a)*r)}x.closePath();x.fillStyle='#151719';x.fill()}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=renderer.capabilities.getMaxAnisotropy();return t}
const ball=new THREE.Mesh(new THREE.SphereGeometry(BALL_R,48,32),new THREE.MeshPhysicalMaterial({map:ballTexture(),roughness:.45,clearcoat:.06}));ball.castShadow=true;ball.position.set(0,BALL_R,0);scene.add(ball);
const B={v:new THREE.Vector3(),w:new THREE.Vector3(),mass:.43,Cd:.25,restitution:.75,friction:.42,magnus:.00035,owner:null};
function nearestTeammate(){let best=null,d=1e9;for(const p of players)if(p.userData.team===0&&p!==active){const n=p.position.distanceTo(active.position);if(n<d){d=n;best=p}}return best}
function kick(power,curve=0){const dir=new THREE.Vector3(1,0,0).applyAxisAngle(new THREE.Vector3(0,1,0),active.rotation.y);B.owner=null;B.v.copy(dir.multiplyScalar(power));B.v.y=Math.max(1.4,power*.28);B.w.set(0,curve,curve*.35);B.last=performance.now()/1000;ball.position.copy(active.position).add(new THREE.Vector3(0,.05,0)).add(dir.multiplyScalar(1));}
function pass(){if(ball.position.distanceTo(active.position)>1.5)return;const t=nearestTeammate();const dir=t?t.position.clone().sub(ball.position):new THREE.Vector3(1,0,0);dir.y=0;dir.normalize();B.owner=null;B.v.copy(dir.multiplyScalar(12));B.v.y=.35;B.w.set(0,2,0);statusEl.textContent='PASS'}
function shoot(){if(ball.position.distanceTo(active.position)>1.5)return;const p=14;const dir=new THREE.Vector3(1,0,0).applyAxisAngle(new THREE.Vector3(0,1,0),active.rotation.y);B.owner=null;B.v.copy(dir.multiplyScalar(p));B.v.y=4.2;B.w.set(0,6,2);statusEl.textContent='SHOT'}
function resetBall(){ball.position.set(0,BALL_R,0);B.v.set(0,0,0);B.w.set(0,0,0);B.owner=null;goalLock=.5;statusEl.textContent='BALL RESET'}
function switchPlayer(){const candidates=players.filter(p=>p.userData.team===0);let best=candidates[0],d=1e9;for(const p of candidates){const n=p.position.distanceTo(ball.position);if(n<d){d=n;best=p}}active.userData.marker.visible=false;active=best;active.userData.marker.visible=true}

function separatePlayers(){for(let i=0;i<players.length;i++)for(let j=i+1;j<players.length;j++){const a=players[i],b=players[j],d=new THREE.Vector3(a.position.x-b.position.x,0,a.position.z-b.position.z),len=d.length();if(len>0&&len<PLAYER_R*2){d.multiplyScalar((PLAYER_R*2-len)/len*.5);a.position.add(d);b.position.sub(d)}}}
function ai(dt){const carrier=active;for(const p of players)if(p.userData.team===1){const u=p.userData;u.tackle=Math.max(0,u.tackle-dt);let target=u.base.clone();target.y=.9;const ballInfluence=clamp((ball.position.x+52.5)/105,0,1);target.x=THREE.MathUtils.lerp(u.base.x,Math.min(18,ball.position.x+8),.45);target.z=THREE.MathUtils.lerp(u.base.z,ball.position.z*.72,.55);if(ball.position.x>20&&p.position.distanceTo(carrier.position)<18)target.copy(carrier.position);const dir=target.clone().sub(p.position);dir.y=0;const dist=dir.length();if(dist>.25){dir.normalize();const speed=dist<3?2.5:5.1;u.v.lerp(dir.multiplyScalar(speed),1-Math.exp(-7*dt));p.position.addScaledVector(u.v,dt);p.rotation.y=Math.atan2(u.v.x,u.v.z)}p.position.x=clamp(p.position.x,-FIELD.HL+.7,FIELD.HL-.7);p.position.z=clamp(p.position.z,-FIELD.HW+.7,FIELD.HW-.7);if(p.position.distanceTo(carrier.position)<1.2&&u.tackle<=0){u.tackle=.9;if(Math.random()<.62){B.owner=p;B.v.set(0,0,0);ball.position.copy(p.position).add(new THREE.Vector3(-.6,0,0));carrier.userData.stun=.45;statusEl.textContent='TACKLED'}}if(ball.position.x>35&&Math.abs(ball.position.z)<20&&p.position.x>25&&ball.position.distanceTo(p.position)<7&&Math.random()<dt*1.8){B.owner=null;B.v.set(-11,2.5,(Math.random()-.5)*5);statusEl.textContent='CLEARANCE'}}}
function ballPhysics(dt){if(B.owner){ball.position.lerp(B.owner.position.clone().add(new THREE.Vector3(-.65,BALL_R,0)),1-Math.exp(-20*dt));B.v.set(0,0,0);return}B.v.y-=9.81*dt;const speed=B.v.length();if(speed>0){const drag=Math.min(.98,B.Cd*dt*speed);B.v.addScaledVector(B.v,-drag);const magnus=new THREE.Vector3().crossVectors(B.w,B.v).multiplyScalar(B.magnus);B.v.addScaledVector(magnus,dt);B.w.multiplyScalar(Math.exp(-B.w.length()*dt*.04));}ball.position.addScaledVector(B.v,dt);if(ball.position.y<=BALL_R){ball.position.y=BALL_R;if(B.v.y<0)B.v.y=-B.v.y*B.restitution;B.v.x*=Math.max(0,1-B.friction*dt*2.2);B.v.z*=Math.max(0,1-B.friction*dt*2.2);B.w.multiplyScalar(.96)}ball.rotation.x+=B.w.z*dt+ B.v.z*dt*2;ball.rotation.z-=B.w.x*dt+B.v.x*dt*2;ball.rotation.y+=B.w.y*dt+B.v.x*dt*.03;for(const p of players){const d=new THREE.Vector3(ball.position.x-p.position.x,0,ball.position.z-p.position.z),len=d.length();if(len<1.5&&ball.position.y<1.2&&p.userData.team===0&&p===active&&B.v.length()<2){B.owner=p}}for(const p of players){const d=new THREE.Vector3(ball.position.x-p.position.x,0,ball.position.z-p.position.z),len=d.length();if(len<.53&&ball.position.y<1.0&&len>0){d.normalize();B.v.addScaledVector(d,(.53-len)*8);}}if(Math.abs(ball.position.z)>FIELD.HW-BALL_R){ball.position.z=clamp(ball.position.z,-FIELD.HW+BALL_R,FIELD.HW-BALL_R);B.v.z*=-.55}if(ball.position.x>FIELD.HL+3.5||ball.position.x<-FIELD.HL-3.5)resetBall();if(ball.position.x>FIELD.HL&&Math.abs(ball.position.z)<3.66&&ball.position.y<2.44&&goalLock<=0){score[0]++;scoreEl.textContent=`${score[0]} - ${score[1]}`;statusEl.textContent='GOAL!';goalLock=1.4;resetBall()}if(ball.position.x<-FIELD.HL&&Math.abs(ball.position.z)<3.66&&ball.position.y<2.44&&goalLock<=0){score[1]++;scoreEl.textContent=`${score[0]} - ${score[1]}`;statusEl.textContent='AWAY GOAL';goalLock=1.4;resetBall()}}
function cameraUpdate(dt){const b=ball.position;let target=active.position.clone();if(cameraMode===0){const desired=new THREE.Vector3(active.position.x-28,19,active.position.z+24);camera.position.lerp(desired,1-Math.exp(-3*dt));camera.lookAt(new THREE.Vector3((active.position.x+b.x)*.5,0,b.z*.5))}else if(cameraMode===1){camera.position.lerp(new THREE.Vector3(0,72,.1),1-Math.exp(-3*dt));camera.lookAt(new THREE.Vector3(0,0,0))}else{const desired=active.position.clone().add(new THREE.Vector3(-11,8,12));camera.position.lerp(desired,1-Math.exp(-5*dt));camera.lookAt(target)}}
function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;matchTime+=dt;goalLock=Math.max(0,goalLock-dt);if(consume('q'))switchPlayer();if(consume('r'))resetBall();if(consume('c')){cameraMode=(cameraMode+1)%3;statusEl.textContent=['TELE-BROADCAST','OVERHEAD','FOLLOW'][cameraMode]}if(consume('e'))pass();if(consume('space'))shoot();const move=new THREE.Vector3((keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),0,(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0));if(active.userData.stun>0)active.userData.stun-=dt;else if(move.lengthSq()){move.normalize();const speed=keys.shift?9:6;active.userData.v.lerp(move.multiplyScalar(speed),1-Math.exp(-10*dt));active.position.addScaledVector(active.userData.v,dt);active.rotation.y=Math.atan2(active.userData.v.x,active.userData.v.z)}else active.userData.v.multiplyScalar(Math.exp(-8*dt));active.position.x=clamp(active.position.x,-FIELD.HL+.7,FIELD.HL-.7);active.position.z=clamp(active.position.z,-FIELD.HW+.7,FIELD.HW-.7);ballPhysics(dt);ai(dt);separatePlayers();cameraUpdate(dt);clockEl.textContent=`${String(Math.floor(matchTime/60)).padStart(2,'0')}:${String(Math.floor(matchTime%60)).padStart(2,'0')}`;requestAnimationFrame(loop);renderer.render(scene,camera)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight,false)});camera.position.set(-30,18,25);requestAnimationFrame(loop);
